name: CI - Pytest + Selenium + Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        id: setup-chrome

      - name: Verify Chrome installation
        run: |
          google-chrome --version
          chromedriver --version || echo "Chromedriver handled by webdriver_manager"

      - name: Run Tests with Pytest + Allure
        run: |
          pytest -v --alluredir=reports/allure-results

      - name: Upload Allure Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
