name: Selenium Pytest Automation with Allure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Download Chrome & ChromeDriver for Selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Run Tests with Allure
        run: |
          pytest --alluredir=reports/

      - name: Upload Allure Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: reports/
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
